# Generated by Django 4.0.4 on 2022-05-14 09:13

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='source',
            field=models.ImageField(blank=True, upload_to=photos.models.get_owner_upload_path),
        ),
    ]
